// lib/sparePartsData.ts
// Single source of truth for spare parts inventory per machine

export interface SparePart {
  id: string;
  itemName: string;
  partNumber: string;
  spec: string; // Ampere / Size / Type depending on machine
  specLabel: string; // "Ampere" | "Size" | "Type"
  d: number; // daily demand
  L: number; // lead time (days)
  SS: number; // safety stock
  currentStock: number;
  machineId: string;
}

export type StockStatus = "good" | "warn" | "bad";

export function computeROP(d: number, L: number, SS: number): number {
  return d * L + SS;
}

export function getStockStatus(currentStock: number, rop: number): StockStatus {
  if (currentStock <= rop) return "bad";
  if (currentStock <= rop * 1.2) return "warn";
  return "good";
}

export const spareParts: SparePart[] = [
  // ─── PLASMA CUTTER ───────────────────────────────────────────────
  {
    id: "pc-001",
    machineId: "plasma-cutter",
    itemName: "Cutting Tip",
    partNumber: "21-1061",
    spec: "50A",
    specLabel: "Ampere",
    d: 8,
    L: 2,
    SS: 16,
    currentStock: 40,
  },
  {
    id: "pc-002",
    machineId: "plasma-cutter",
    itemName: "Cutting Tip",
    partNumber: "35-1053",
    spec: "100A",
    specLabel: "Ampere",
    d: 10,
    L: 2,
    SS: 20,
    currentStock: 45,
  },
  {
    id: "pc-003",
    machineId: "plasma-cutter",
    itemName: "Cutting Tip",
    partNumber: "35-1055",
    spec: "200A",
    specLabel: "Ampere",
    d: 12,
    L: 3,
    SS: 24,
    currentStock: 62,
  },
  {
    id: "pc-004",
    machineId: "plasma-cutter",
    itemName: "Electrode",
    partNumber: "35-1078",
    spec: "50A",
    specLabel: "Ampere",
    d: 6,
    L: 2,
    SS: 12,
    currentStock: 28,
  },
  {
    id: "pc-005",
    machineId: "plasma-cutter",
    itemName: "Electrode",
    partNumber: "35-1071",
    spec: "100A",
    specLabel: "Ampere",
    d: 8,
    L: 3,
    SS: 16,
    currentStock: 42,
  },
  {
    id: "pc-006",
    machineId: "plasma-cutter",
    itemName: "Electrode",
    partNumber: "35-1085",
    spec: "200A",
    specLabel: "Ampere",
    d: 10,
    L: 3,
    SS: 20,
    currentStock: 55,
  },
  {
    id: "pc-007",
    machineId: "plasma-cutter",
    itemName: "Shield Cap",
    partNumber: "35-1027",
    spec: "100A",
    specLabel: "Ampere",
    d: 3,
    L: 3,
    SS: 6,
    currentStock: 16,
  },
  {
    id: "pc-008",
    machineId: "plasma-cutter",
    itemName: "Shield Cap",
    partNumber: "35-1030",
    spec: "200A",
    specLabel: "Ampere",
    d: 4,
    L: 3,
    SS: 8,
    currentStock: 20,
  },
  {
    id: "pc-009",
    machineId: "plasma-cutter",
    itemName: "Shield Gas Distributor",
    partNumber: "35-1280",
    spec: "200A",
    specLabel: "Ampere",
    d: 2,
    L: 3,
    SS: 4,
    currentStock: 10,
  },
  {
    id: "pc-010",
    machineId: "plasma-cutter",
    itemName: "Shield Gas Distributor",
    partNumber: "35-1272",
    spec: "100A",
    specLabel: "Ampere",
    d: 2,
    L: 3,
    SS: 4,
    currentStock: 10,
  },

  // ─── LASER CUTTING ───────────────────────────────────────────────
  {
    id: "lc-001",
    machineId: "laser-cutter",
    itemName: "Cutting Tip",
    partNumber: "1.02.0351",
    spec: "D27.9 x 4.1mm",
    specLabel: "Size",
    d: 5,
    L: 2,
    SS: 10,
    currentStock: 24,
  },
  {
    id: "lc-002",
    machineId: "laser-cutter",
    itemName: "Cutting Tip",
    partNumber: "NA",
    spec: "D37 x 7.0mm",
    specLabel: "Size",
    d: 4,
    L: 2,
    SS: 8,
    currentStock: 18,
  },
  {
    id: "lc-003",
    machineId: "laser-cutter",
    itemName: "Electrode",
    partNumber: "1.02.0067",
    spec: "H15-S-1.2",
    specLabel: "Size",
    d: 2,
    L: 3,
    SS: 4,
    currentStock: 10,
  },
  {
    id: "lc-004",
    machineId: "laser-cutter",
    itemName: "Electrode",
    partNumber: "1.02.0068",
    spec: "H15-S-1.5",
    specLabel: "Size",
    d: 2,
    L: 3,
    SS: 4,
    currentStock: 10,
  },
  {
    id: "lc-005",
    machineId: "laser-cutter",
    itemName: "Electrode",
    partNumber: "1.02.0070",
    spec: "H15-S-2.0",
    specLabel: "Size",
    d: 3,
    L: 3,
    SS: 6,
    currentStock: 15,
  },
  {
    id: "lc-006",
    machineId: "laser-cutter",
    itemName: "Electrode",
    partNumber: "1.02.0071",
    spec: "H15-S-2.5",
    specLabel: "Size",
    d: 3,
    L: 3,
    SS: 6,
    currentStock: 15,
  },
  {
    id: "lc-007",
    machineId: "laser-cutter",
    itemName: "Electrode",
    partNumber: "1.02.0072",
    spec: "H15-S-3.0",
    specLabel: "Size",
    d: 3,
    L: 3,
    SS: 6,
    currentStock: 15,
  },
  {
    id: "lc-008",
    machineId: "laser-cutter",
    itemName: "Electrode",
    partNumber: "1.02.0074",
    spec: "H15-S-4.0",
    specLabel: "Size",
    d: 4,
    L: 2,
    SS: 8,
    currentStock: 18,
  },
  {
    id: "lc-009",
    machineId: "laser-cutter",
    itemName: "Composite Nozzle",
    partNumber: "1.02.0059",
    spec: "H15-D-1.5",
    specLabel: "Size",
    d: 4,
    L: 2,
    SS: 8,
    currentStock: 18,
  },
  {
    id: "lc-010",
    machineId: "laser-cutter",
    itemName: "Composite Nozzle",
    partNumber: "1.02.0061",
    spec: "H15-D-2.0",
    specLabel: "Size",
    d: 4,
    L: 2,
    SS: 8,
    currentStock: 18,
  },
  {
    id: "lc-011",
    machineId: "laser-cutter",
    itemName: "Composite Nozzle",
    partNumber: "1.02.0063",
    spec: "H15-D-3.0",
    specLabel: "Size",
    d: 3,
    L: 2,
    SS: 6,
    currentStock: 12,
  },
  {
    id: "lc-012",
    machineId: "laser-cutter",
    itemName: "Composite Nozzle",
    partNumber: "1.02.0065",
    spec: "H15-D-4.0",
    specLabel: "Size",
    d: 3,
    L: 4,
    SS: 6,
    currentStock: 18,
  },
  {
    id: "lc-013",
    machineId: "laser-cutter",
    itemName: "Ceramic Body",
    partNumber: "1.02.0112",
    spec: "D32",
    specLabel: "Size",
    d: 1,
    L: 2,
    SS: 3,
    currentStock: 5,
  },
  {
    id: "lc-014",
    machineId: "laser-cutter",
    itemName: "Distilled Water",
    partNumber: "DW-01",
    spec: "7 liters",
    specLabel: "Size",
    d: 2,
    L: 1,
    SS: 10,
    currentStock: 12,
  },

  // ─── MILLING MACHINE ─────────────────────────────────────────────
  {
    id: "ml-001",
    machineId: "milling-machine",
    itemName: "End Mill (Carbide)",
    partNumber: "EM-06",
    spec: "6 mm",
    specLabel: "Type",
    d: 2,
    L: 3,
    SS: 4,
    currentStock: 10,
  },
  {
    id: "ml-002",
    machineId: "milling-machine",
    itemName: "End Mill (Carbide)",
    partNumber: "EM-10",
    spec: "10 mm",
    specLabel: "Type",
    d: 2,
    L: 3,
    SS: 4,
    currentStock: 10,
  },
  {
    id: "ml-003",
    machineId: "milling-machine",
    itemName: "End Mill (Carbide)",
    partNumber: "EM-16",
    spec: "16 mm",
    specLabel: "Type",
    d: 1,
    L: 4,
    SS: 2,
    currentStock: 6,
  },
  {
    id: "ml-004",
    machineId: "milling-machine",
    itemName: "Face Mill Insert",
    partNumber: "FM-1204",
    spec: "Carbide Insert",
    specLabel: "Type",
    d: 6,
    L: 2,
    SS: 12,
    currentStock: 26,
  },
  {
    id: "ml-005",
    machineId: "milling-machine",
    itemName: "Drill Bit",
    partNumber: "DR-08",
    spec: "8 mm HSS",
    specLabel: "Type",
    d: 3,
    L: 3,
    SS: 6,
    currentStock: 15,
  },
  {
    id: "ml-006",
    machineId: "milling-machine",
    itemName: "Drill Bit",
    partNumber: "DR-12",
    spec: "12 mm HSS",
    specLabel: "Type",
    d: 2,
    L: 3,
    SS: 4,
    currentStock: 10,
  },
  {
    id: "ml-007",
    machineId: "milling-machine",
    itemName: "Tap Tool",
    partNumber: "TP-M8",
    spec: "M8 Thread",
    specLabel: "Type",
    d: 1,
    L: 4,
    SS: 2,
    currentStock: 6,
  },
  {
    id: "ml-008",
    machineId: "milling-machine",
    itemName: "Tap Tool",
    partNumber: "TP-M12",
    spec: "M12 Thread",
    specLabel: "Type",
    d: 1,
    L: 4,
    SS: 2,
    currentStock: 6,
  },
  {
    id: "ml-009",
    machineId: "milling-machine",
    itemName: "Coolant (Cutting Fluid)",
    partNumber: "CL-01",
    spec: "Liquid (Liters)",
    specLabel: "Type",
    d: 10,
    L: 2,
    SS: 20,
    currentStock: 42,
  },
  {
    id: "ml-010",
    machineId: "milling-machine",
    itemName: "Way Oil",
    partNumber: "LO-01",
    spec: "ISO VG68",
    specLabel: "Type",
    d: 2,
    L: 3,
    SS: 4,
    currentStock: 10,
  },
  {
    id: "ml-011",
    machineId: "milling-machine",
    itemName: "Filter",
    partNumber: "WF-01",
    spec: "Coolant Filter",
    specLabel: "Type",
    d: 1,
    L: 3,
    SS: 3,
    currentStock: 6,
  },

  // ─── LATHE MACHINE ───────────────────────────────────────────────
  {
    id: "lt-001",
    machineId: "lathe-machine",
    itemName: "Turning Insert",
    partNumber: "TNMG-1604",
    spec: "Carbide Insert",
    specLabel: "Type",
    d: 8,
    L: 2,
    SS: 16,
    currentStock: 34,
  },
  {
    id: "lt-002",
    machineId: "lathe-machine",
    itemName: "Turning Insert",
    partNumber: "CNMG-1204",
    spec: "Carbide Insert",
    specLabel: "Type",
    d: 6,
    L: 2,
    SS: 12,
    currentStock: 24,
  },
  {
    id: "lt-003",
    machineId: "lathe-machine",
    itemName: "Boring Bar Insert",
    partNumber: "SCLCR-06",
    spec: "Internal Turning",
    specLabel: "Type",
    d: 4,
    L: 3,
    SS: 8,
    currentStock: 20,
  },
  {
    id: "lt-004",
    machineId: "lathe-machine",
    itemName: "Parting Tool Blade",
    partNumber: "PT-2",
    spec: "2 mm Width",
    specLabel: "Type",
    d: 3,
    L: 3,
    SS: 6,
    currentStock: 16,
  },
  {
    id: "lt-005",
    machineId: "lathe-machine",
    itemName: "Threading Insert",
    partNumber: "16ER-AG60",
    spec: "External Thread",
    specLabel: "Type",
    d: 2,
    L: 4,
    SS: 4,
    currentStock: 12,
  },
  {
    id: "lt-006",
    machineId: "lathe-machine",
    itemName: "Drill Bit (Lathe use)",
    partNumber: "DR-10",
    spec: "Ø10 mm HSS",
    specLabel: "Type",
    d: 3,
    L: 3,
    SS: 6,
    currentStock: 15,
  },
  {
    id: "lt-007",
    machineId: "lathe-machine",
    itemName: "Live Center Tip",
    partNumber: "LC-01",
    spec: "Morse Taper Tip",
    specLabel: "Type",
    d: 1,
    L: 5,
    SS: 2,
    currentStock: 7,
  },
  {
    id: "lt-008",
    machineId: "lathe-machine",
    itemName: "Cutting Fluid (Coolant)",
    partNumber: "CL-01",
    spec: "Liquid (Liters)",
    specLabel: "Type",
    d: 8,
    L: 2,
    SS: 16,
    currentStock: 34,
  },
  {
    id: "lt-009",
    machineId: "lathe-machine",
    itemName: "Lubricant",
    partNumber: "LO-01",
    spec: "ISO VG68",
    specLabel: "Type",
    d: 2,
    L: 3,
    SS: 4,
    currentStock: 10,
  },
  {
    id: "lt-010",
    machineId: "lathe-machine",
    itemName: "Chuck Jaw Pads",
    partNumber: "CJ-01",
    spec: "Soft Jaw Insert",
    specLabel: "Type",
    d: 1,
    L: 5,
    SS: 2,
    currentStock: 7,
  },
];

export function getSparePartsByMachine(machineId: string): SparePart[] {
  return spareParts.filter((p) => p.machineId === machineId);
}
